### POST
POST http://localhost:3000/animals
Content-Type: application/json

{
  "name": "Jopie",
  "age": 12,
  "breed": "Persian"
}

### GET
GET http://localhost:3000/animals

### GET by id
GET http://localhost:3000/animals/65a6575373d98e92bf3b6914

